version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "5100:5100" 
    networks:
      - bridge_network
networks:
  bridge_network:
    driver: bridge
